import "../../global.css";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const cx = (...classes) => classes.filter(Boolean).join(" ");

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className={cx(
        "text-black bg-white dark:text-white dark:bg-black",
        GeistSans.variable,
        GeistMono.variable
      )}
    >
      <body className='antialiased w-full mt-8 px-5 lg:mx-auto '>
        <main className='flex-auto min-w-0 mt-6 flex flex-col md:px-0'>
          {children}
        </main>
      </body>
    </html>
  );
}
